version: '3'

services:
    db:  
        build: .\db
        container_name: db
        ports:
            - 3306:3306
              

    scraper:
        build: .\scraper
        container_name: scraper
        links: 
            - db
        command: tail -F anything